apiVersion: v1
kind: Service
metadata:
  name: api-template-quarkus-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007
  selector:
    app: api-template-quarkus