apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-template-quarkus-deployment
  annotations:
    commitID: "8f494a39258590272215575b6259e27807b4cf4f"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-template-quarkus
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api-template-quarkus
    spec:
      containers:
        - name: api-template
          image: 'xavelo/api-template-quarkus:8f494a39258590272215575b6259e27807b4cf4f'
          ports:
            - containerPort: 80
