apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-template-quarkus-deployment
  annotations:
    commitID: "4b917722d2c05bd3a8a4bd123d5895597ad26c5c"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-template-quarkus
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api-template-quarkus
    spec:
      containers:
        - name: api-template
          image: 'xavelo/api-template-quarkus:4b917722d2c05bd3a8a4bd123d5895597ad26c5c'
          ports:
            - containerPort: 80
