apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-template-quarkus-deployment
  annotations:
    commitID: "0b66feae63f1493f71eeaae3afc48146145f1145"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-template-quarkus
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api-template-quarkus
    spec:
      containers:
        - name: api-template
          image: 'xavelo/api-template-quarkus:0b66feae63f1493f71eeaae3afc48146145f1145'
          ports:
            - containerPort: 80
