apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-template-quarkus-deployment
  annotations:
    commitID: "6808f656e05a80b01d459e257b6cd1ab12f59e31"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-template-quarkus
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api-template-quarkus
    spec:
      containers:
        - name: api-template
          image: 'xavelo/api-template-quarkus:6808f656e05a80b01d459e257b6cd1ab12f59e31'
          ports:
            - containerPort: 80
