apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-template-quarkus-deployment
  annotations:
    commitID: "1bf94ae2719f0d18e424f876da27b00fa260f841"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-template-quarkus
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api-template-quarkus
    spec:
      containers:
        - name: api-template
          image: 'xavelo/api-template-quarkus:1bf94ae2719f0d18e424f876da27b00fa260f841'
          ports:
            - containerPort: 80
